[package]
name = "cls16"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
env_logger = "0.10.0"
log = "0.4.20"
nom = "7.1.3"
nom_locate = "4.2.0"
rustc-hash = "1.1.0"
thiserror = "1.0.48"
